config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/search' => 'search#search'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :voted do
    member do
      post :vote_positive
      post :vote_negative
      post :vote_del
    end
  end

  resources :questions, concerns: [:voted,], shallow: true do
    resource :subscriptions,  only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :answers, concerns: [:voted] do
      resources :comments, only: [:create]
      patch 'set_best', on: :member
    end
  end

  resources :attachments, only: :destroy

  resources :comments, only: [:update, :destroy]

  root to: "questions#index"
  mount ActionCable.server => '/cable'

  namespace 'api' do
    namespace 'v1' do
      resources :profiles  do
        get 'me', on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  after_create :subscribe_author_to_question

  private

  def subscribe_author_to_question
    self.user.subscribe_to(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    respond_with Question.all
  end

  def show
    respond_with Question.find(params[:id])
  end

  def create
    respond_with @question = current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, :gon_question, only: :show
  after_action :publish_question, only: :create

  authorize_resource

  respond_to :js, only: :update

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    respond_with @question.update(question_params)
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def gon_question
    gon.question = @question
    gon.answers = @question.answers
  end

  def build_answer
    @answer = Answer.new(question: @question)
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
        'questions', @question.to_json(include: [:attachments, :user], methods: :vote_rating)
    )
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
div id="Question-#{question.id}"
  .panel.panel-primary
    .panel-heading
      - cache question do
        = link_to question.title, question, class: "question-link"
        = render 'shared/vote_menu', votable: question
        = render 'shared/subscription_menu', question: question
    .panel-body
      - cache question do
        p = question.body
        - if question.attachments.present?
          p Attachments:
          ul
            = render question.attachments
        .comments
          p Comments:
          = render question.comments
      - if current_user
        .new_comment
          = form_for [question, question.comments.build], :html => {:class => "display"}, remote: true do |f|
            = hidden_field_tag :commentable, 'question'
            p
              = f.label :body
            p
              = f.text_area :body

            = f.submit 'Create comment', class: "btn btn-primary btn-xs"
            .errors

    - if current_user&.author_of? question
      .panel-footer
        => link_to 'Delete', question, :method => :delete, :title => "Delete question", class: "delete-answer-link btn btn-primary btn-xs"
        => link_to 'Edit', "", class: 'edit-question-link delete-answer-link btn btn-primary btn-xs', data: {question_id: question.id}
        p
          = form_for question, remote: true, html: {id: "edit-question-#{question.id}"}  do |f|
            p
              = f.label :title, "Title"
              = f.text_area :title
            p
              = f.label :body, "Body"
              = f.text_area :body
            p
              = f.submit 'Save question'

app/views/questions/index.html.slim
.questions-list
  = render @questions

p.text-center = link_to 'Ask question', new_question_path, class: "btn btn-primary btn-lg"

app/views/questions/new.html.slim
.panel.panel-default
  .panel-body
    = form_for @question do |f|
      p
        = f.label :title
      p
        = f.text_field :title
      p
        = f.label :body
      p
        = f.text_area :body
      .panel.panel-default
          .panel-body
            = f.fields_for :attachments, @question.attachments.build do |attachment|
              = render 'attachments/attachment_fields', f: attachment
            .links
              = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_fields'
      - if @question.errors.any?
        - @question.errors.full_messages.each do |msg|
          p = msg
      p
        = f.submit 'Create', class: "btn btn-primary btn-md"

app/views/questions/show.html.slim
- cache @question do
  .question
    = render @question
  .answers
    = render @question.answers

p
  - if current_user.present?
    .panel.panel-default
      .panel-body
        = form_for [@question, @answer], remote: true do |f|
          - if @answer.errors.any?
            - @answer.errors.full_messages.each do |msg|
              p = msg
          p
            = f.label :body
          p
            = f.text_area :body
          .panel.panel-default
            .panel-body
              = f.fields_for :attachments, @answer.attachments.build  do |attachment|
                = render 'attachments/attachment_fields', f: attachment
              .links
                = link_to_add_association 'add file', f, :attachments, partial: 'attachments/attachment_fields'

          = f.submit 'Create answer', class: "btn btn-primary btn-md"
          .errors

app/views/questions/update.js.erb
$('.notice').html('<%= j render 'shared/notice' %>');
<% if @question.errors.any? %>
  $('.notice').append("<%= @question.errors.full_messages.join('<br>') %>");
<% else %>
  $("#Question-<%= @question.id %>").html('<%= j render @question %>');
  $('.edit-question-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      question_id = $(this).data('questionId');
      $('form#edit-question-' + question_id).show();
  });
<% end %>