config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/search' => 'search#search'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :voted do
    member do
      post :vote_positive
      post :vote_negative
      post :vote_del
    end
  end

  resources :questions, concerns: [:voted,], shallow: true do
    resource :subscriptions,  only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :answers, concerns: [:voted] do
      resources :comments, only: [:create]
      patch 'set_best', on: :member
    end
  end

  resources :attachments, only: :destroy

  resources :comments, only: [:update, :destroy]

  root to: "questions#index"
  mount ActionCable.server => '/cable'

  namespace 'api' do
    namespace 'v1' do
      resources :profiles  do
        get 'me', on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_notice.js.erb
<%= bootstrap_flash %>

app/views/shared/_subscription_menu.html.slim
.btn-group.subscribe-group.btn-group-xs.pull-right role="group"
  => link_to 'subscribe', question_subscriptions_path(question), method: :post, remote: true, data: {type: :json},
        class: "btn btn-default subs subscribe", style: "#{"display: none" unless current_user && !current_user.subscribed_to?(question)}"

  => link_to 'unsubscribe', question_subscriptions_path(question), method: :delete, remote: true, data: { type: :json },
        class: "btn btn-default subs unsubscribe", style: "#{"display: none" unless current_user && current_user.subscribed_to?(question)}"

app/views/shared/_vote_menu.html.slim
.btn-group.btn-group-xs.pull-right role="group"
  => link_to 'vote +1', polymorphic_path(votable, action: :vote_positive), method: :post, remote: true,
          data: {type: :json}, class: "btn btn-default vote vote_positive",
          style: "#{"display: none" unless current_user && votable.can_vote?(current_user) }"

  span class="btn btn-default vote_raiting" = "rating: " + votable.vote_rating.to_s

  => link_to 'vote -1', polymorphic_path(votable, action: :vote_negative), method: :post, remote: true,
          data: { type: :json }, class: "btn btn-default vote vote_negative",
          style: "#{"display: none" unless current_user && votable.can_vote?(current_user) }"

  => link_to 'delete vote', polymorphic_path(votable, action: :vote_del), method: :post, remote: true,
          data: { type: :json }, class: "btn btn-danger vote_delete",
          style: "#{"display: none" unless current_user && votable.vote_by(current_user) }"