config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/search' => 'search#search'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :voted do
    member do
      post :vote_positive
      post :vote_negative
      post :vote_del
    end
  end

  resources :questions, concerns: [:voted,], shallow: true do
    resource :subscriptions,  only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :answers, concerns: [:voted] do
      resources :comments, only: [:create]
      patch 'set_best', on: :member
    end
  end

  resources :attachments, only: :destroy

  resources :comments, only: [:update, :destroy]

  root to: "questions#index"
  mount ActionCable.server => '/cable'

  namespace 'api' do
    namespace 'v1' do
      resources :profiles  do
        get 'me', on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  default_scope { order(best: :desc, created_at: :asc) }

  after_create :answer_notify

  def set_best
    self.transaction do
      self.question.answers.update_all(best: false)
      self.update!(best: true)
    end
  end

  private

  def answer_notify
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:destroy, :update, :set_best]
  after_action :publish_answer, only: :create

  authorize_resource

  respond_to :js

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user_id: current_user.id)))
  end

  def update
    respond_with @answer.update(answer_params)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def set_best
    respond_with(@answer.set_best)
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
        "question-#{@answer.question.id}", @answer.to_json(include: [:attachments, :user], methods: :vote_rating)
    )
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def index
    respond_with Question.find(params[:question_id]).answers.to_json
  end

  def show
    respond_with Answer.find(params[:id])
  end

  def create
    respond_with @answer = Answer.create(answer_params.merge(question_id: params[:question_id], user_id: current_resource_owner.id))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id="Answer-#{answer.id}" class="#{ 'best panel-danger' if answer.best? }"
  .panel.panel-default
    .panel-body
      - cache answer do
        p = answer.body
        - if answer.attachments.present?
          p Attachments:
          ul
            = render answer.attachments

        .comments
          p Comments:
          = render answer.comments

      - if current_user
        .new_comment
          = form_for [answer, answer.comments.build], :html => {:class => "display"}, remote: true do |f|
            = hidden_field_tag :commentable, 'answer'
            p
              = f.label :body
            p
              = f.text_area :body

            = f.submit 'Create comment', class: "btn btn-primary btn-xs"
            .errors
      - cache answer do
        = render 'shared/vote_menu', votable: answer
    .panel-footer
      - if current_user&.author_of? @answer.question
        => link_to 'Set best answer', set_best_answer_path(answer), method: :patch, remote: true, class: "set-best-answer-link btn btn-primary btn-xs"
      - if current_user&.author_of? answer
        => link_to 'Delete', answer, class: "delete-answer-link btn btn-primary btn-xs", data: { answer_id: answer.id }, method: :delete, title: "Delete answer", remote: true
        => link_to 'Edit', "", class: 'edit-answer-link btn btn-primary btn-xs', data: { answer_id: answer.id }
        p
          =form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" }  do |f|
            p = f.label :body, "Answer"
            p = f.text_area :body
            p = f.submit 'Save'

app/views/answers/create.js.erb
$('.notice').html('<%= j render 'shared/notice' %>');
<% if @answer.errors.any? %>
  $('.new_answer .errors').html("<%= @answer.errors.full_messages.join('<br>') %>");
<% else %>
  $('textarea#answer_body').val('');
  $('.answers').append('<%= j render @answer %>');
  $('#new_answer .nested-fields').remove();
<% end %>

app/views/answers/destroy.js.erb
$('.notice').html('<%= j render 'shared/notice' %>');
$('div#Answer-<%= @answer.id %>').remove();

app/views/answers/set_best.js.erb
$('.notice').html('<%= j render 'shared/notice' %>');
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/update.js.erb
$('.notice').html('<%= j render 'shared/notice' %>');
<% if @answer.errors.any? %>
  $('.notice').append("<%= @answer.errors.full_messages.join('<br>') %>");
<% else %>
  $("#Answer-<%= @answer.id %>").html('<%= j render @answer %>');
  $('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
  });
<% end %>